# Generated by Django 3.0.4 on 2020-05-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='thumb',
            field=models.ImageField(blank=True, default='default', upload_to=''),
        ),
    ]
