# Generated by Django 3.0.4 on 2020-05-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affer', '0004_auto_20200530_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='thumb',
        ),
    ]
