# Generated by Django 3.0.4 on 2020-05-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0007_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
